services:
  hybridcoach-pg:
    image: postgres:15
    container_name: hybridcoach-pg
    environment:
      POSTGRES_USER: hybridcoach
      POSTGRES_PASSWORD: HybridCoach789878987!asdasdasd
      POSTGRES_DB: hybridcoach_dev
    ports:
      - "5432:5432"
    volumes:
      - hybridcoach_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  hybridcoach_data:
